version: "3.9"

services:
  draza:
    build: .
    image: draza:1.0.0  # Taguj svoj imidž
    container_name: wwwsql
    restart: always          # Bitno za produkciju
    ports:
      - "3000:3000"
    # U produkciji nema volumena za kod, samo za logove ili bazu ako treba